version: '3'

volumes:
    xauth:
    x11-unix:

services:
  db:
    image: postgres
    container_name: measure24_db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  web:
    build: ./docker/web
    container_name: measure24
    command: ["sh", "/home/start.sh"]
    volumes:
      - .:/measure24
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DJANGO_SU_NAME
      - DJANGO_SU_EMAIL
      - DJANGO_SU_PASSWORD
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_PORT
    depends_on:
      - db
      - geckodriver
      - xvfb
      - x11vnc
  geckodriver:
      build: ./docker/geckodriver
      volumes:
          - xauth:/tmp/xauth
          - x11-unix:/tmp/.X11-unix
      ports:
          - 4444:4444
      environment:
          DISPLAY: :0
          XAUTHORITY: /tmp/xauth/Xauthority
  xvfb:
      image: quay.io/cvlibrary/xvfb
      volumes:
          - xauth:/tmp/xauth
          - x11-unix:/tmp/.X11-unix
      ipc: "host"
      command: -screen 0 1920x1080x24
  x11vnc:
      image: quay.io/cvlibrary/x11vnc
      depends_on:
          - xvfb
      volumes:
          - xauth:/tmp/xauth
          - x11-unix:/tmp/.X11-unix
      command: -q -nopw -auth /tmp/xauth/Xauthority
      environment:
          DISPLAY: :0
      ipc: "host"
      ports:
          - 5900:5900
  cronjobs:
    build: ./docker/web
    container_name: measure24_cron
    command: ["python", "/measure24/measure24/manage.py", "cronserver"]
    volumes:
      - .:/measure24
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DJANGO_SU_NAME
      - DJANGO_SU_EMAIL
      - DJANGO_SU_PASSWORD
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_PORT
    depends_on:
      - web