version: '3'

volumes:
    xauth:
    x11-unix:

services:
  db:
    image: postgres
    container_name: measure24_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  web:
    build: ./docker/web
    container_name: measure24
    command: ["sh", "/home/start.sh"]
    volumes:
      - .:/measure24
    ports:
      - "8000:8000"
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_PORT
      - DB_ENGINE
      - DJANGO_SU_NAME
      - DJANGO_SU_EMAIL
      - DJANGO_SU_PASSWORD
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_PORT
    depends_on:
      - db
      - geckodriver
      - xvfb
      - x11vnc
  geckodriver:
      build: ./docker/geckodriver
      volumes:
          - xauth:/tmp/xauth
          - x11-unix:/tmp/.X11-unix
      environment:
          DISPLAY: :0
          XAUTHORITY: /tmp/xauth/Xauthority
  xvfb:
      image: quay.io/cvlibrary/xvfb
      volumes:
          - xauth:/tmp/xauth
          - x11-unix:/tmp/.X11-unix
      ipc: "host"
      command: -screen 0 1920x1080x24
  x11vnc:
      image: quay.io/cvlibrary/x11vnc
      depends_on:
          - xvfb
      volumes:
          - xauth:/tmp/xauth
          - x11-unix:/tmp/.X11-unix
      command: -q -nopw -auth /tmp/xauth/Xauthority
      environment:
          DISPLAY: :0
      ipc: "host"
  cronjobs:
    build: ./docker/web
    container_name: measure24_cron
    command: ["sh", "/measure24/docker/web/corn_start.sh"]
    volumes:
      - .:/measure24
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_PORT
      - DB_ENGINE
      - DJANGO_SU_NAME
      - DJANGO_SU_EMAIL
      - DJANGO_SU_PASSWORD
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_PORT
    depends_on:
      - web