version: '3'

volumes:
    xauth:
    x11-unix:
    postgres-data:

services:
  db:
    image: postgres
    container_name: measure24_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
  web:
    build:
      context: ./measure24
      dockerfile: ./../docker/web/Dockerfile
    container_name: measure24
    command: ["sh", "/home/start.sh"]
#    volumes:
#      - .:/measure24
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - geckodriver
      - xvfb
      - x11vnc
  geckodriver:
      build:
        context: ./measure24
        dockerfile: ./../docker/geckodriver/Dockerfile
      volumes:
          - xauth:/tmp/xauth
          - x11-unix:/tmp/.X11-unix
      environment:
          DISPLAY: :0
          XAUTHORITY: /tmp/xauth/Xauthority
  xvfb:
      image: quay.io/cvlibrary/xvfb
      volumes:
          - xauth:/tmp/xauth
          - x11-unix:/tmp/.X11-unix
      ipc: "host"
      command: -screen 0 1920x1080x24
  x11vnc:
      image: quay.io/cvlibrary/x11vnc
      depends_on:
          - xvfb
      volumes:
          - xauth:/tmp/xauth
          - x11-unix:/tmp/.X11-unix
      command: -q -nopw -auth /tmp/xauth/Xauthority
      environment:
          DISPLAY: :0
      ipc: "host"
  cronjobs:
    build:
      context: ./measure24
      dockerfile: ./../docker/web/Dockerfile
    container_name: measure24_cron
    command: ["sh", "/measure24/measure24/corn_start.sh"]
#    volumes:
#      - .:/measure24
    env_file:
      - ./.env
    depends_on:
      - web
