version: '3'

volumes:
    xauth:
    x11-unix:

services:
  db:
    image: postgres
    container_name: measure24_db
    environment:
      - POSTGRES_USER=measure24_django
      - POSTGRES_PASSWORD=QIwODtIPAzCymO4kZfZO
      - POSTGRES_DB=measure24_db
  web:
    build: ./docker/web
    container_name: measure24
    volumes:
      - .:/measure24
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SU_NAME=admin
      - DJANGO_SU_EMAIL=root@localhost
      - DJANGO_SU_PASSWORD=passwordtochange123
    depends_on:
      - db
      - geckodriver
      - xvfb
      - x11vnc
  geckodriver:
      build: ./docker/geckodriver
      volumes:
          - /etc/machine-id:/etc/machine-id
          - xauth:/tmp/xauth
          - x11-unix:/tmp/.X11-unix
      ports:
          - 4444:4444
      environment:
          DISPLAY: :0
          XAUTHORITY: /tmp/xauth/Xauthority
  xvfb:
      image: quay.io/cvlibrary/xvfb
      volumes:
          - xauth:/tmp/xauth
          - x11-unix:/tmp/.X11-unix
      ipc: "host"
      command: -screen 0 1920x1080x24
  x11vnc:
      image: quay.io/cvlibrary/x11vnc
      depends_on:
          - xvfb
      volumes:
          - xauth:/tmp/xauth
          - x11-unix:/tmp/.X11-unix
      command: -q -nopw -auth /tmp/xauth/Xauthority
      environment:
          DISPLAY: :0
      ipc: "host"
      ports:
          - 5900:5900